---
name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: lsst-dm/build-and-push@main
        id: build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          image: ${{ github.repository }}
          push: true
